# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Expose stdin/stdout as needed by MCP
CMD ["node", "dist/main.js"]
